### ISSUE TITLE
New to reclaim-Plugin

### ISSUE THREAD

**Issue by heibie** [espresto/reclaim-social-media#143]
Hi
this isn't kind of an issue, but more an introduction to myself. i came across the idea of reclaim-social-media [during #rp13](http://www.bielinski.de/2013/11/reclaim-social-media-teil-1-um-was-gehts/) in berlin and always wanted to use it, and now i did. 

since december 2014 i'm running my [own reclaim-site](http://reclaim.bielinski.de) and i'm quite impressed, how well this allready works.

i wrote [some](http://www.bielinski.de/2015/01/reclaim-social-media-installieren/) [blogposts](http://www.bielinski.de/2015/01/reclaim-social-media-ein-neuer-anfang/) (in german) about the plugin.

during installation, i came across some bugs and had, of course, many feature-ideas. so right now, my question is: how can i contribute to the project?

i have also medium programming skills (php, frontend css/html) and lots of wordpress-know-how, but i think, i'm not on the level to contribute to such an open-source-project in adequate quality. so perhaps, i could do some documentation/translation work, bug-test or think about new feature requests ;-)

but the main question is: is this project still under development? and if not, how can we get it back to work? 

heiko

**Comment by diplix** [comment]
right now nobody activly develops reclaim. if you have a working contribution or bug fix, i’ll merge it. if you have feature-requests or ideas, add an issue. maybe not right away, but i’ll try to work it out, discuss it or ask for help. my programming skills are well below medium, but there have been quite some contributors that helped with that. 

so i guess another step to revive activity in this project is documenting bugs and requesting features.

**Comment by moschlar** [comment]
Motivated by your two blog entries, I've also just set up an instance - though it took me a while to get the Facebook mod to work because it requires PHP with CURL support, but at least that's documented now, so there's a little bit of activity! ;)

**Comment by heibie** [comment]
ok, felix, as far as i can guess from reading some of your blog-posts, we both have about the same medium-programming-skills ;-)
so, would it be ok, if i start to update some of the documentation in the github-wiki and perhaps add some new pages? i'll also try to figure out and sum up the feature-wishes and bugs i can find, working with the plugin for the next weeks and add them to the issue tracker, where we can discuss them.

**Comment by diplix** [comment]
sounds great.

**Comment by pheraph** [comment]
Didn't anyone of you hit Twitter's rate limit I described in #141? Would love to use reclaim, buto the broken initial (?) Twitter import stopped me.

**Comment by diplix** [comment]
AFAIK the twitter-api does not allow the retrival of more than 1000 tweets. there ist a way around this, by ordering an archive at twitter and importing that. that has not been done for reclaim yet.=

**Comment by heibie** [comment]
my experience also was, that, on my initial setup of reclaim, only about 1000 tweets (and some extra favs) where imported to the system.

[here is a chart](https://dev.twitter.com/rest/public/rate-limits) with request-limits for the twitter-api. i haven't looked up yet, which api-call the reclaim-plugin uses.

one workaround for that problem could be, as felix already mentioned, doing an initial import of the twitter-archive, which every user can request from twitter. the twitter-archive is in json.format so you would need a plugin, which does an import of a potentially huge json-file (which i couldn't find on quick research)

or you first [convert the json-file](http://ctrlq.org/code/19433-twitter-json-to-rss) to some kind of xml/rss and then use one of the [rss-importers](https://wordpress.org/plugins/wp-rss-multi-importer/) for wordpress (which i haven't yet tested).

right now, [i'm using](http://tweetnest.bielinski.de/) another tool called [tweetnest](http://pongsocket.com/tweetnest/), which does exactly, what you want. it imports the whole twitter-archive, and after that, catches all your follow-up tweets. this works very well, but it's completely separated from wordpress.

so there seem to be basically two options:
1. use some external tool/skript/plugin to do the initial import
2. integrate the initial twitter import in reclaim

perhaps tweetnest is a good place to get some inspiration for solving the problem in reclaim?

**Comment by diplix** [comment]
i’m closing this issue, there is an older issue concerning the twitter archive import: #132
